# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 467cd5c68b9fe9d611bfa73223062a47395678b5677c3dc4dd7311d0b3ee842fb1b676ebbcf6ffaffae55ac01c038c15b71ea41ae617932b3070026496f744f7

test:
  secret_key_base: 0af310726594581c8fcd9d1f9258aa687cf703fa3dc82dc5f11ca756fabf16df90d89e244a22ad0d1bfb748eff33a34801e1854cbce659034872b4255805ea7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
